project:
  type: website

website:
  description: "Thoughts on AI-assisted development, tools, and the craft of teaching with code"
  site-url: https://antisimplistic.com
  title: "Antisimplistic Blog"
  open-graph: true
  twitter-card: true
  comments:
    giscus:
      repo: olearydj/blog
      category: "Comments"
      mapping: pathname
      reactions-enabled: true
      input-position: top
      theme:
        light: light
        dark: dark_dimmed
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/olearydj
      - icon: twitter
        href: https://twitter.com/antisimplistic
format:
  html:
    theme:
      - cosmo
      - custom.scss
    include-in-header:
      - text: |
          <script defer src="https://cloud.umami.is/script.js" data-website-id="c9802eff-4b9f-4c9c-acd2-5072c22d9eab"></script>
