project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://antisimplistic.com
  title: "Antisimplistic Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/olearydj
      - icon: twitter
        href: https://twitter.com/antisimplistic
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
